/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
  './App.{js,ts,tsx}',
  './components/**/*.{js,ts,tsx}',
  './screens/**/*.{js,ts,tsx}',
  './navigation/**/*.{js,ts,tsx}',
  './context/**/*.{js,ts,tsx}',
  './hooks/**/*.{js,ts,tsx}',
  './utils/**/*.{js,ts,tsx}',
],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      "colors": {
        "surface-container-highest": "#efe0d6",
        "primary-container": "#4b3621",
        "primary-fixed": "#fedcbe",
        "on-surface-variant": "#4e453d",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e4c27d",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#f5e5dc",
        "surface-dim": "#e6d7ce",
        "on-background": "#221a14",
        "outline-variant": "#d2c4ba",
        "on-tertiary-fixed": "#261a00",
        "secondary-fixed": "#f0e1c5",
        "surface-variant": "#efe0d6",
        "tertiary-container": "#4c3700",
        "surface": "#fff8f5",
        "on-tertiary-fixed-variant": "#5a4309",
        "surface-container-low": "#fff1e8",
        "surface-container": "#fbebe1",
        "tertiary-fixed": "#ffdf9f",
        "on-primary-fixed-variant": "#59422c",
        "surface-container-lowest": "#ffffff",
        "background": "#fff8f5",
        "on-secondary-fixed": "#221b0a",
        "surface-tint": "#725a42",
        "on-tertiary-container": "#c0a05f",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-bright": "#fff8f5",
        "on-surface": "#221a14",
        "on-error-container": "#93000a",
        "secondary-container": "#f0e1c5",
        "inverse-primary": "#e1c1a4",
        "inverse-on-surface": "#fdeee4",
        "secondary-fixed-dim": "#d3c5aa",
        "on-primary-fixed": "#291806",
        "on-secondary-container": "#6e634d",
        "primary-fixed-dim": "#e1c1a4",
        "on-secondary": "#ffffff",
        "secondary": "#685d47",
        "outline": "#80756c",
        "on-secondary-fixed-variant": "#4f4631",
        "primary": "#33210d",
        "inverse-surface": "#372f28",
        "on-primary-container": "#bd9f83",
        "on-error": "#ffffff",
        "tertiary": "#312200"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "24px",
        "xl": "80px",
        "lg": "48px",
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
